config/routes.rb
Runbook::Application.routes.draw do
  
  devise_for :users

  resources :step_validations

  match 'runs/:id/finish' => 'runs#finish'

  resources :users

  resources :books do 
    resources :steps    
    resources :runs   
  end

  resources :runs do 
    member do 
      get 'finish'
      get 'sendmail'
   end
  end

  resources :steps

  root :to => 'books#index'

end

app/models/book_step.rb
class BookStep < ActiveRecord::Base
  attr_accessible :book_id, :description, :id, :title

  belongs_to :book
end

app/controllers/book_steps_controller.rb
class BookStepsController < ApplicationController

  before_filter :get_book

  # GET /book_steps
  # GET /book_steps.json
  def index
    @book_steps = @book.book_steps.all
    @book = @book

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @book_steps }
    end
  end

  # GET /book_steps/1
  # GET /book_steps/1.json
  def show
    @book_step = BookStep.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book_step }
    end
  end

  # GET /book_steps/new
  # GET /book_steps/new.json
  def new
    @book_step = BookStep.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book_step }
    end
  end

  # GET /book_steps/1/edit
  def edit
    @book_step = BookStep.find(params[:id])
  end

  # POST /book_steps
  # POST /book_steps.json
  def create
    @book_step = BookStep.new(params[:book_step])

    respond_to do |format|
      if @book_step.save
        format.html { redirect_to @book_step, notice: 'Book step was successfully created.' }
        format.json { render json: @book_step, status: :created, location: @book_step }
      else
        format.html { render action: "new" }
        format.json { render json: @book_step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /book_steps/1
  # PUT /book_steps/1.json
  def update
    @book_step = BookStep.find(params[:id])

    respond_to do |format|
      if @book_step.update_attributes(params[:book_step])
        format.html { redirect_to @book_step, notice: 'Book step was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book_step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_steps/1
  # DELETE /book_steps/1.json
  def destroy
    @book_step = BookStep.find(params[:id])
    @book_step.destroy

    respond_to do |format|
      format.html { redirect_to book_steps_url }
      format.json { head :no_content }
    end
  end

  private 

  def get_book
    @book = Book.find(params[:book_id])
  end

end

app/helpers/book_steps_helper.rb
module BookStepsHelper
end

app/views/book_steps/_form.html.erb
<%= form_for(@book_step) do |f| %>
  <% if @book_step.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book_step.errors.count, "error") %> prohibited this book_step from being saved:</h2>

      <ul>
      <% @book_step.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :book_id %><br />
    <%= f.number_field :book_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/book_steps/edit.html.erb
<%= content_for :title, 'ACME Ltd Run Books > Edit Run Book' %>

<%= render 'form' %>

<%= link_to 'Show', @book_step %> |
<%= link_to 'Back', book_steps_path %>

app/views/book_steps/index.html.erb
<h1>Listing book_steps</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Book</th>
    <th>Title</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @book_steps.each do |book_step| %>
  <tr>
    <td><%= book_step.id %></td>
    <td><%= book_step.book_id %></td>
    <td><%= book_step.title %></td>
    <td><%= book_step.description %></td>
    <td><%= link_to 'Show', book_book_step_path(book_step.book,book_step) %></td>
    <td><%= link_to 'Edit', edit_book_step_path(book_step) %></td>
    <td><%= link_to 'Destroy', book_step, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Book step', new_book_step_path %>

app/views/book_steps/new.html.erb
<%= content_for :title, 'ACME Ltd Run Books > Add Run Book' %>


<%= render 'form' %>

<%= link_to 'Back', book_steps_path %>

app/views/book_steps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @book_step.id %>
</p>

<p>
  <b>Book:</b>
  <%= @book_step.book_id %>
</p>

<p>
  <b>Title:</b>
  <%= @book_step.title %>
</p>

<p>
  <b>Description:</b>
  <%= @book_step.description %>
</p>


<%= link_to 'Edit', edit_book_step_path(@book_step) %> |
<%= link_to 'Back', book_steps_path %>