config/routes.rb
Runbook::Application.routes.draw do
  
  devise_for :users

  resources :step_validations

  match 'runs/:id/finish' => 'runs#finish'

  resources :users

  resources :books do 
    resources :steps    
    resources :runs   
  end

  resources :runs do 
    member do 
      get 'finish'
      get 'sendmail'
   end
  end

  resources :steps

  root :to => 'books#index'

end

app/models/run_step.rb
class RunStep < ActiveRecord::Base
  attr_accessible :book_step_id, :id, :run_id

  belongs_to :run
  belongs_to :book_step

end

app/controllers/run_steps_controller.rb
class RunStepsController < ApplicationController
  # GET /run_steps
  # GET /run_steps.json
  def index
    @run_steps = RunStep.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @run_steps }
    end
  end

  # GET /run_steps/1
  # GET /run_steps/1.json
  def show
    @run_step = RunStep.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @run_step }
    end
  end

  # GET /run_steps/new
  # GET /run_steps/new.json
  def new
    @run_step = RunStep.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @run_step }
    end
  end

  # GET /run_steps/1/edit
  def edit
    @run_step = RunStep.find(params[:id])
  end

  # POST /run_steps
  # POST /run_steps.json
  def create
    @run_step = RunStep.new(params[:run_step])

    respond_to do |format|
      if @run_step.save
        format.html { redirect_to @run_step, notice: 'Run step was successfully created.' }
        format.json { render json: @run_step, status: :created, location: @run_step }
      else
        format.html { render action: "new" }
        format.json { render json: @run_step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /run_steps/1
  # PUT /run_steps/1.json
  def update
    @run_step = RunStep.find(params[:id])

    respond_to do |format|
      if @run_step.update_attributes(params[:run_step])
        format.html { redirect_to @run_step, notice: 'Run step was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @run_step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /run_steps/1
  # DELETE /run_steps/1.json
  def destroy
    @run_step = RunStep.find(params[:id])
    @run_step.destroy

    respond_to do |format|
      format.html { redirect_to run_steps_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/run_steps_helper.rb
module RunStepsHelper
end

app/views/run_steps/_form.html.erb
<%= form_for(@run_step) do |f| %>
  <% if @run_step.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@run_step.errors.count, "error") %> prohibited this run_step from being saved:</h2>

      <ul>
      <% @run_step.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :run_id %><br />
    <%= f.number_field :run_id %>
  </div>
  <div class="field">
    <%= f.label :book_step_id %><br />
    <%= f.number_field :book_step_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/run_steps/edit.html.erb
<h1>Editing run_step</h1>

<%= render 'form' %>

<%= link_to 'Show', @run_step %> |
<%= link_to 'Back', run_steps_path %>

app/views/run_steps/index.html.erb
<h3>All Run Steps</h3>

<table>
  <tr>
    <th>Id</th>
    <th>Run</th>
    <th>Book step</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @run_steps.each do |run_step| %>
  <tr>
    <td><%= run_step.id %></td>
    <td><%= run_step.run_id %></td>
    <td><%= run_step.book_step_id %></td>
    <td><%= link_to 'Show', run_step %></td>
    <td><%= link_to 'Edit', edit_run_step_path(run_step) %></td>
    <td><%= link_to 'Destroy', run_step, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Run step', new_run_step_path %>

app/views/run_steps/new.html.erb
<h1>New run_step</h1>

<%= render 'form' %>

<%= link_to 'Back', run_steps_path %>

app/views/run_steps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @run_step.id %>
</p>

<p>
  <b>Run:</b>
  <%= @run_step.run_id %>
</p>

<p>
  <b>Book step:</b>
 
</p>
sdf	


<%= link_to 'Edit', edit_run_step_path(@run_step) %> |
<%= link_to 'Back', run_steps_path %>