config/routes.rb
Runbook::Application.routes.draw do
  
  devise_for :users

  resources :step_validations

  match 'runs/:id/finish' => 'runs#finish'

  resources :users

  resources :books do 
    resources :steps    
    resources :runs   
  end

  resources :runs do 
    member do 
      get 'finish'
      get 'sendmail'
   end
  end

  resources :steps

  root :to => 'books#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :description, :id, :title

  has_many :steps
  has_many :runs

  validates_presence_of :title, :description

  def number_of_open_runs
    completed_runs = runs.all
    completed_runs.nil? ? 0 : completed_runs.size
  end

  def most_recent_run
    completed_runs = runs.first( :order => 'CREATED_AT DESC' )
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # GET /books
  # GET /books.json
  def index
    @books = Book.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to books_path, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for(@book,  :html => { :class => "form label-inline"} ) do |f| %>

<% if @book.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
  <ul>
    <% @book.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :title %>
  <%= f.text_field :title, :class => 'medium', :size => 50 %>
</div>
<div class="field">
  <%= f.label :description %>
  <%= f.text_area :description, :class => 'medium', :rows => 5, :cols => 100 %>
</div>

<div class="actions">
  <button class="btn btn-blue btn-check">
	<p><%= link_to 'Back', books_path %></p>
  </button>

  <button class="btn btn-blue btn-check">
	<p_Fo><%= link_to_submit 'Create' %></p>
</button>
</div>
<% end %>

app/views/books/edit.html.erb
<h2>Edit Run Book</h2>

<%= render 'form' %>

app/views/books/index.html.erb
<%= content_for :title, 'ACME Ltd Run Books ' %>

<div class="department">
  <div style="clear:both"/>
  


  <h2>Our Run Books</h2>

  <table border=1 cellspacing=0 cellpadding=5 rel="datatable">
	<thead>
	  <tr>
		<th>Title</th>
		<th>Number Of Steps</th>
		<th>Last Run</th>
		<th>Edit</th>
		<th>Delete</th>
	  </tr>
	</thead>
   	<tbody>
	  <% @books.each_with_index do |book,index| %>
	  <tr>
		<td width="300"><%= link_to book.title, book %></td>
		<td width="150"><%= book.steps.size %></td>
		<td width="250">
		  <%= link_to book.most_recent_run.created_at.strftime("%A %d %B %Y - %H:%M"), 
			  book.most_recent_run unless book.most_recent_run.nil? %>
		</td>
		<td width="50"><%= link_to image_tag('pencil.png'), edit_book_path(book) %>
		<td width="50"><%= link_to image_tag('cross.png'), book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	  </tr>		 
	  <% end %>
  </table>

  <button class="btn btn-blue btn-check">
	<p><%= link_to 'Create New Run Book', new_book_path %></p>
  </button>

</div>

app/views/books/new.html.erb
<%= content_for :title, 'ACME Ltd Run Books > Add Run Book' %>

<%= render 'form' %>

app/views/books/show.html.erb
<%= content_for :title, 'ACME Ltd Run Books > ' + @book.title %>

<h2><%= @book.title %></h2>

<p><i><%= @book.description %></i></p>

<% if !@book.steps.empty? || !@book.runs.empty? %>

<div class="tab_container">
  <ul class="tabs"> 
	
	<% if !@book.steps.empty? %>
	<li><a href="#tab1">Steps</a></li>
	<% end %>  

	<% if !@book.runs.empty? %>
	<li><a href="#tab2">Runs</a></li>
	<% end %>
  </ul> 

  <div class="tab_content_container"> 
	
	<% if !@book.steps.empty? %>	
	<div id="tab1" class="tab_content"> 
	  <div class="department">
		<table border=1 cellspacing=0 cellpadding=5     rel="datatable" id="example">
		  <thead>
			<tr>
			  <th>Step Number</th>
			  <th>Title</th>
			  <th>Edit</th>
			  <!--th>Sort</th-->
			  <th>Delete</th>				  
			</tr>
		  </thead>	
		  <tbody>
			<% @book.steps.each_with_index do |step,index| %>
			<tr>
			  <td width="100"><%= index %></td>
			  <td width="300"><%= step.title %></td>
			  <td width="50"><%= link_to image_tag('pencil.png') , edit_book_step_path(step.book,step) %>
			  <!--td width="50">
				<%= image_tag 'sort_asc.png'%>
				<%= image_tag 'sort_desc.png'%>
			  </td-->
			  <td width="50"><%= link_to image_tag('cross.png'), step, method: :delete, data: { confirm: 'Are you sure?' } %></td>

			</tr>
			<% end %>
		  </tbody>
		</table>
	  </div>
	</div> 
	<% end %>
	<!-- #tab1 -->

	<% if !@book.runs.empty? %>
	<div id="tab2" class="tab_content"> 
	  <div class="department">			
		<table border=1 cellspacing=0 cellpadding=5    rel="datatable" id="example">
		  <thead>
			<tr>
			  <th width="100">Step</th>
			  <th width="200">User</th>
			  <th width="250">Start Time</th>
			</tr>
		  </thead>	
		  <tbody>
			<% @book.runs.each_with_index do |run,index| %>
			<tr>
			  <td><%= index %></td> 
			  <td><%= run.user.email %>
			  <td><%= run.created_at.strftime("%A %d %B %Y - %H:%M") %></td>
			</tr>
			<% end %>
		  </tbody>
		</table>
	  </div>
	</div> 
	<% end %>
	<!-- #tab2 -->
	
  </div> 

</div> <!-- .tab_container -->
<% end %>
</div>
<br/><br/></br></br>

<!-- Navigation buttons -->
<% if !@book.steps.empty? %> 
<button class="btn btn-blue btn-check"> 
  <p><%= link_to 'Execute Run Book', new_book_run_path(@book) %></p>
</button>
<% end %>
<button class="btn btn-blue btn-check"> 
  <p><%= link_to 'Add Step To Run Book', new_book_step_path(@book) %></p>
</button>