config/routes.rb
Runbook::Application.routes.draw do
  
  devise_for :users

  resources :step_validations

  match 'runs/:id/finish' => 'runs#finish'

  resources :users

  resources :books do 
    resources :steps    
    resources :runs   
  end

  resources :runs do 
    member do 
      get 'finish'
      get 'sendmail'
   end
  end

  resources :steps

  root :to => 'books#index'

end

app/models/run.rb
class Run < ActiveRecord::Base
  attr_accessible :book_id, :complete, :id, :user_id, :created_at

  belongs_to :book
  
  belongs_to :user

  def in_role?(role)
  	true
  end

  def append_step_output output
    puts 'APPENDING STEP OUTPUT - ' + output
  end

end
 

app/controllers/runs_controller.rb
class RunsController < ApplicationController
  # GET /runs
  # GET /runs.json
  def index
    @runs = Run.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @runs }
    end
  end

  # GET /runs/1
  # GET /runs/1.json
  def show
    @run = Run.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @run }
    end
  end

  # GET /runs/new
  # GET /runs/new.json
  def new
    book = Book.find(params[:book_id])    
    @run = book.runs.build


      
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @run }
    end
  end
 
  # GET /runs/1/edit
  def edit
    @run = Run.find(params[:id])
  end

  # POST /runs
  # POST /runs.json
  def create
    @run = Run.new(params[:run])
    @run.user_id = current_user.id

    respond_to do |format|
      if @run.save
        format.html { redirect_to @run.book.steps.first, notice: 'Run was successfully created.' }                
      else
        format.html { render action: "new" }        
      end
    end
  end

  # PUT /runs/1
  # PUT /runs/1.json
  def update
    @run = Run.find(params[:id])

    respond_to do |format|
      if @run.update_attributes(params[:run])
        format.html { redirect_to @run, notice: 'Run was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @run.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /runs/1
  # DELETE /runs/1.json
  def destroy
    @run = Run.find(params[:id])
    @run.destroy

    respond_to do |format|
      format.html { redirect_to runs_url }
      format.json { head :no_content }
    end
  end

  def finish
      @run = Run.find(params[:id])
      @run.complete = true
      @run.save
  end

  def sendmail
      puts 'Sending Mail!'
      @run = Run.find(params[:id])
      respond_to do |format|
        format.html { render action: "finish" }
      end

  end


end

app/helpers/runs_helper.rb
module RunsHelper
end

app/views/runs/.#_form.html.erb
benjaminwootton@Benjamins-MacBook-Air.local.2990

app/views/runs/.#show.html.erb
benjaminwootton@Benjamins-MacBook-Air.local.2990

app/views/runs/_form.html.erb
<%= form_for([@run.book,@run]) do |f| %>
  <% if @run.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@run.errors.count, "error") %> prohibited this run from being saved:</h2>

      <ul>
      <% @run.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="hidden">
    <%= f.hidden_field :book_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/runs/edit.html.erb
<h1>Editing run</h1>

<%= render 'form' %>

<%= link_to 'Show', @run %> |
<%= link_to 'Back', runs_path %>

app/views/runs/finish.html.erb
<h2>Run Complete</h2>


<button class="btn btn-blue btn-check"> 
	<%= link_to 'Send A Mail Of This Run', method: :post, :controller => 'runs', :id => @run.id, :action => 'sendmail'  %>
</button>

<button class="btn btn-blue btn-check"> 
	<%= link_to 'Done', @run.book %>
</button>

<br/><br/>

app/views/runs/index.html.erb
<%= content_for :title, 'Runs' %>

<h3>All Runs</h3>

<table>
  <tr>
    <th>Id</th>
    <th>User</th>
    <th>Book</th>
    <th>Complete</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @runs.each do |run| %>
  <tr>
    <td><%= run.id %></td>
    <td><%= run.user_id %></td>
    <td><%= run.book_id %></td>
    <td><%= run.complete %></td>
    <td><%= link_to 'Show', run %></td>
    <td><%= link_to 'Edit', edit_run_path(run) %></td>
    <td><%= link_to 'Destroy', run, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Run', new_run_path %>

app/views/runs/new.html.erb
<h2>Confirm Run</h2>

<p><i>Are you sure you wish to run this Run Book?</i></p>

<%= render 'form' %>

</br>

<!--
<% if !@run.book.runs.nil? %>
	<p><b>ALERT: This RunBook is currently being ran <%= @run.book.runs.size %> times</b><br>
<% end %> -->

app/views/runs/show.html.erb
<p id="notice"><%= notice %></p>

<h3>Run</h3>

<p>
  <b>Id:</b>
  <%= @run.id %>
</p>

<p>
  <b>User:</b>
  <%= @run.user_id %>
</p>

<p>
  <b>Book:</b>
  <%= @run.book_id %>
</p>

<p>
  <b>Complete:</b>
  <%= @run.complete %>
</p>

<%= link_to 'Book', step_path(@run.book.steps.first) %>


<p>
<%= link_to 'Edit', edit_run_path(@run) %> |
<%= link_to 'Back', runs_path %>
</p>